version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.9.0'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: linter
          command: npm run lint
      - run:
          name: scss linter
          command: npm run lint-scss
      - run:
          name: audit critical and high issues
          command: npm audit | grep -E "(High)" -B3 -A10
      - run:
          name: test
          command: npm test
